version: '3.8'

networks:
  kafka-net:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    networks:
      kafka-net:
        ipv4_address: 172.16.238.10
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    build: .
    networks:
      kafka-net:
        ipv4_address: 172.16.238.11
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=172.16.238.10:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://172.16.238.11:9092
